### ISSUE TITLE
《嬉笑集》校對

### ISSUE THREAD

**Issue by szc126** [wordshk/yue_references#4]
PDF第5頁〈酈食其〉
- 「吹起牛屁」→「吹起牛𡲎」？

PDF第10頁〈老子騎青牛過函谷（甲子本）〉
- 「滿嘴」→「滿(口𦙼)」？
- 另有分注「紫氣東來」

PDF第9頁〈題陶淵明種菊圖（甲子本）〉
- 「挽隻荲」→「挽隻(𥫗里)」？

**Comment by wordshk** [comment]
- 「吹牛屁」可能係當年嘅電子化嘅人睇到啲筆記打咗個交叉話其實係個屁字？ 暫時唔覺得特登搵個生僻unicode字去代替會好啲。

<img width="105" alt="Screenshot 2024-05-26 at 23 56 41" src="https://github.com/wordshk/yue_references/assets/117781/163eb56b-ed6f-4aae-b797-0fb54847f17e">

- 「滿嘴」 應該都係咁上下

- 挽隻(𥫗里) 嗰度我會改返佢

**Comment by wordshk** [comment]
Fixed in https://github.com/wordshk/yue_references/commit/4b07d7547332c84cdf5cdca8bb71795c9b56a8f9
